name: Get token and build UI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1.2.0

      - name: Get token
        id: get_token
        env:
          KB_EMAIL: ${{ secrets.KB_EMAIL }}
          KB_PW: ${{ secrets.KB_PW }}
        run: |
          TOKEN=$(curl -s -X POST "https://api.kickbase.com/v4/user/login" \
            -H "Content-Type: application/json" \
            -d "{\"em\":\"$KB_EMAIL\", \"pass\":\"$KB_PW\"}" | jq -r '.tkn')

          echo "VITE_TOKEN=$TOKEN" >> $GITHUB_ENV
          echo "::set-output name=token::$TOKEN"

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build frontend
        env:
          VITE_TOKEN: ${{ steps.get_token.outputs.token }}
        run: bun run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
